### ISSUE TITLE
File name convention

### ISSUE THREAD

**Issue by stravid** [stravid/slotcars#11]
We should find a convention on how to name files. Once we have one, we should rename all the files!

Suggestions please :-)

**Comment by roboshoes** [comment]
### suggestion
- all lower case
- underscore to seperate words
- package name part of file name
- spec part of name

### example

**car_controller.js.coffee**
**car_controller_spec.js.coffee**
**car_view.js.coffee**

_controller_, _view_, etc. should always be part of the name - no matter if it's already in there folder.

**Comment by bmedicke** [comment]
:+1:

**Comment by roboshoes** [comment]
I could see that some of the files have been renamed to that convention already. I continued i my branch feature/track-design to rename some more of them.

**Comment by tombu** [comment]
By now controllers and views match the above naming pattern.
The only inconsistency left is the naming of the template files. Some of them include 'view' some don´t. I like the convention including the 'view'.

e.g. **game_view_template.js.hjs** instead of **game_template.js.hjs**

The only exception is the naming of the models on which we agreed (at least @DominikGuzei and me) to leave the 'model' part (like rails does)

**Comment by stravid** [comment]
I agree that the template of the `game_view.js.coffee` should be named `game_view_template.js.hjs`
